name: taskendar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: 0.19.0
  go_router: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true