name: taskendar
description: A new Flutter project
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  go_router: ^14.3.0
  flutter_localized_locales: ^2.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  uuid: ^4.2.2
  table_calendar: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
      - family: OpenSans
        fonts:
          - asset: lib/assets/fonts/OpenSans.ttf
            weight: 700
      - family: Roboto
        fonts:
          - asset: lib/assets/fonts/Roboto.ttf
            weight: 700

flutter_intl:
  enabled: true