// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZ6wj5FbTAc2r3l6ivJaURVVdNiKKLL0',
    appId: '1:194814647114:web:c6e3b0eff94f535d31ffb3',
    messagingSenderId: '194814647114',
    projectId: 'taskendar-412ad',
    authDomain: 'taskendar-412ad.firebaseapp.com',
    storageBucket: 'taskendar-412ad.appspot.com',
    measurementId: 'G-5VKM5G1D4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnjOxJ6ZEp6gmAjL4E0LZdY8i_LQr-V0s',
    appId: '1:194814647114:android:e79527ae9e1ef08f31ffb3',
    messagingSenderId: '194814647114',
    projectId: 'taskendar-412ad',
    storageBucket: 'taskendar-412ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3R5sNVeJjMZYmyzCCdGZYBcr_9lbVj7s',
    appId: '1:194814647114:ios:99cf2c09117e754031ffb3',
    messagingSenderId: '194814647114',
    projectId: 'taskendar-412ad',
    storageBucket: 'taskendar-412ad.appspot.com',
    iosBundleId: 'com.example.taskendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3R5sNVeJjMZYmyzCCdGZYBcr_9lbVj7s',
    appId: '1:194814647114:ios:99cf2c09117e754031ffb3',
    messagingSenderId: '194814647114',
    projectId: 'taskendar-412ad',
    storageBucket: 'taskendar-412ad.appspot.com',
    iosBundleId: 'com.example.taskendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZ6wj5FbTAc2r3l6ivJaURVVdNiKKLL0',
    appId: '1:194814647114:web:1c314dcf64d72d4a31ffb3',
    messagingSenderId: '194814647114',
    projectId: 'taskendar-412ad',
    authDomain: 'taskendar-412ad.firebaseapp.com',
    storageBucket: 'taskendar-412ad.appspot.com',
    measurementId: 'G-KYXZ7732XC',
  );
}
